import { index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const profiles = sqliteTable('profiles', { userId: text('user_id').primaryKey(), displayName: text('display_name'), goal: text('goal', { enum: ['lose_fat', 'performance', 'reverse_diet'] }).notNull(), unitSystem: text('unit_system', { enum: ['imperial', 'metric'] }).notNull().default('imperial'), heightCm: real('height_cm'), birthYear: integer('birth_year'), createdAt: integer('created_at', { mode: 'timestamp' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull() });
export const weighIns = sqliteTable('weigh_ins', { id: integer('id').primaryKey({ autoIncrement: true }), userId: text('user_id').notNull().references(() => profiles.userId, { onDelete: 'cascade' }), measuredOn: text('measured_on').notNull(), weightKg: real('weight_kg').notNull(), bodyFatPercent: real('body_fat_percent'), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, (table) => [uniqueIndex('idx_weigh_ins_user_date').on(table.userId, table.measuredOn)]);
export const macroTargets = sqliteTable('macro_targets', { id: integer('id').primaryKey({ autoIncrement: true }), userId: text('user_id').notNull().references(() => profiles.userId, { onDelete: 'cascade' }), effectiveOn: text('effective_on').notNull(), calories: integer('calories').notNull(), proteinG: integer('protein_g').notNull(), carbsG: integer('carbs_g').notNull(), fatG: integer('fat_g').notNull(), reason: text('reason').notNull(), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, (table) => [index('idx_macro_targets_user_effective').on(table.userId, table.effectiveOn)]);
export const dailyNutrition = sqliteTable('daily_nutrition', { id: integer('id').primaryKey({ autoIncrement: true }), userId: text('user_id').notNull().references(() => profiles.userId, { onDelete: 'cascade' }), loggedOn: text('logged_on').notNull(), calories: integer('calories').notNull().default(0), proteinG: real('protein_g').notNull().default(0), carbsG: real('carbs_g').notNull().default(0), fatG: real('fat_g').notNull().default(0), saturatedFatG: real('saturated_fat_g').notNull().default(0), sugarG: real('sugar_g').notNull().default(0), fiberG: real('fiber_g').notNull().default(0), updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull() }, (table) => [uniqueIndex('idx_daily_nutrition_user_date').on(table.userId, table.loggedOn)]);
export const foodEntries = sqliteTable('food_entries', { id: integer('id').primaryKey({ autoIncrement: true }), userId: text('user_id').notNull().references(() => profiles.userId, { onDelete: 'cascade' }), loggedOn: text('logged_on').notNull(), mealType: text('meal_type', { enum: ['breakfast', 'lunch', 'dinner', 'snacks'] }).notNull().default('snacks'), name: text('name').notNull(), detail: text('detail').notNull(), calories: integer('calories').notNull(), proteinG: real('protein_g').notNull(), carbsG: real('carbs_g').notNull(), fatG: real('fat_g').notNull(), saturatedFatG: real('saturated_fat_g').notNull().default(0), sugarG: real('sugar_g').notNull().default(0), fiberG: real('fiber_g').notNull().default(0), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, (table) => [index('idx_food_entries_user_date').on(table.userId, table.loggedOn)]);
export const foodLibrary = sqliteTable('food_library', { id: integer('id').primaryKey({ autoIncrement: true }), name: text('name').notNull(), serving: text('serving').notNull().default('1 serving'), calories: integer('calories').notNull(), proteinG: real('protein_g').notNull(), carbsG: real('carbs_g').notNull(), fatG: real('fat_g').notNull(), saturatedFatG: real('saturated_fat_g').notNull().default(0), sugarG: real('sugar_g').notNull().default(0), fiberG: real('fiber_g').notNull().default(0), source: text('source').notNull().default('elev8'), usageCount: integer('usage_count').notNull().default(0) }, (table) => [uniqueIndex('idx_food_library_name').on(table.name), index('idx_food_library_usage').on(table.usageCount)]);
export const checkIns = sqliteTable('check_ins', { id: integer('id').primaryKey({ autoIncrement: true }), userId: text('user_id').notNull().references(() => profiles.userId, { onDelete: 'cascade' }), checkedInOn: text('checked_in_on').notNull(), trendWeightKg: real('trend_weight_kg').notNull(), calorieAdherence: real('calorie_adherence').notNull(), proteinAdherence: real('protein_adherence').notNull(), recommendation: text('recommendation').notNull(), calorieDelta: integer('calorie_delta').notNull().default(0), acceptedAt: integer('accepted_at', { mode: 'timestamp' }) }, (table) => [index('idx_check_ins_user_date').on(table.userId, table.checkedInOn)]);
export const appleHealthDaily = sqliteTable('apple_health_daily', { id: integer('id').primaryKey({ autoIncrement: true }), userId: text('user_id').notNull().references(() => profiles.userId, { onDelete: 'cascade' }), measuredOn: text('measured_on').notNull(), weightKg: real('weight_kg'), bodyFatPercent: real('body_fat_percent'), activeEnergyKcal: real('active_energy_kcal'), restingEnergyKcal: real('resting_energy_kcal'), syncedAt: integer('synced_at', { mode: 'timestamp' }).notNull() }, (table) => [uniqueIndex('idx_apple_health_user_date').on(table.userId, table.measuredOn)]);
