import { redirect } from "next/navigation";

import SidebarShell from "@/components/SidebarShell";
import { hasRole, requireUserContext } from "@/lib/member";

import PendingCheckInsList from "./PendingCheckInsList";

export default async function CoachNutritionCoachPage() {
  const { error, role, userId } = await requireUserContext();
  if (error || !userId || !hasRole("coach", role)) {
    redirect("/login");
  }

  return (
    <SidebarShell mainClassName="mx-auto w-full max-w-5xl px-5 py-10 lg:py-16">
      <header className="mb-6">
        <p className="text-xs uppercase tracking-[0.2em] text-[var(--text-muted)]">Coach</p>
        <h1 className="mt-1 text-2xl font-semibold text-[var(--text)]">Nutrition Coach</h1>
        <p className="mt-2 max-w-2xl text-sm text-[var(--text-muted)]">
          Pending plan check-ins generated by the daily analyzer. Adherence is the primary
          signal — calorie adjustments are gated on consistent tracking and flagged when
          guardrails are reached.
        </p>
      </header>

      <section>
        <h2 className="mb-3 text-sm font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]">
          Pending Check-Ins
        </h2>
        <PendingCheckInsList />
      </section>
    </SidebarShell>
  );
}
